### PR TITLE
Remove hard coded paths from URI

### PR DESCRIPTION
**Pull request by samueljackson92**
Hi,

I wanted to play with wands locally, but I am hindered by hardcoded paths in the server. Here's a quick PR to fix it.

### CODE REVIEW

**Comment by stefaniereuter** [comment]
@jholloc I think this would be a quick fix to one part of issue #13 . The other idea would be to have a config file on the server side. What do you think makes more sense. I see pros and cons in both options: if you send over the whole path from the client side you need to know exactly where the data is located on the server side I'm not sure if this is the case.  But if you avoid having a server config file you can basically run the server and don't have to specify anything on the server side and can send everything over from the client side. What do you think?

**Comment by samueljackson92** [comment]
@stefaniereuter One idea might be to support both? If you provide an absolute path `/path/to/file.h5` then it works as expected, but the proposed configuration file could support a `working_dir` or similar property allowing you to use paths like `./relative/path/to/file.h5`?

**Comment by stefaniereuter** [comment]
@samueljackson92 I like that. I'll merge the pull request and then add a comment to the issue #13 that this then needs updating in the documentation and the check if an absolute path was sent.

**Review by stefaniereuter — APPROVED** [review]
Approved for merge. As discussed in pull request issue #13 will be modified to support absolute paths and just files.

**Pull request merged**
